### ISSUE TITLE
It does not show all context menu entries

### ISSUE THREAD

**Issue by carlosfrodriguez** [giovdk21/vscode-sublime-merge#1]
Hello,

I've installed your extension and it works very nice, the only problem that I have is that not all entries are shown in the context menu for me.

I only have:
- File history
- Show my commits

I'm new to VSC so I will be very glad if you can help me to make the other menu entries be shown.

Thank you in advance.

((enjoy))
cr

**Comment by giovdk21** [comment]
hi!
this is currently the intended behaviour in order to avoid cluttering the contextual menu.
The two entries you listed are shown when no text is selected, while line history and blame are shown when some text is selected.

You can however use the command palette (`Cmd+Shift+P`) to call any of those at any time.
It's also possible to assign custom keyboard shortcuts to all commands available in VSC (https://code.visualstudio.com/docs/getstarted/keybindings).

If you'd rather have all menu entries shown at all time, I might try to see if I can add a setting to allow it.

**Comment by carlosfrodriguez** [comment]
Hi @giovdk21, I see and it works as you describe, if it possible to add the setting I would love to test it.

**Comment by giovdk21** [comment]
Hi @carlosfrodriguez 
I finally managed to implement this, please let me know if it works as expected!
